export type DegreeLevel = "Associate's" | "Bachelor's" | "Master's" | "Doctoral";

export interface ProgramDetail {
  name: string;
  level: DegreeLevel;
  area: string;
  description: string;
  focusAreas?: string[];
  href: string;
  credits: number;
  duration: string;
  format: string;
  careerPaths: { title: string; salaryRange: string }[];
  sampleCourses: string[];
  accreditations?: string[];
  certPrep?: string;
}

export const ENRICHED_PROGRAMS: ProgramDetail[] = [
  // ── Business ──────────────────────────────────────────────────────
  {
    name: "AA in Business",
    level: "Associate's",
    area: "business",
    description:
      "Launch a career in today's fast-paced business world with foundational coursework in management, marketing, and operations.",
    focusAreas: ["Management", "Marketing", "Operations"],
    href: "/online-degrees/associate/business",
    credits: 60,
    duration: "As few as 18 months",
    format: "100% Online · 5-week courses",
    careerPaths: [
      { title: "Administrative Assistant", salaryRange: "$38K–$52K" },
      { title: "Customer Service Manager", salaryRange: "$42K–$62K" },
      { title: "Sales Representative", salaryRange: "$40K–$65K" },
    ],
    sampleCourses: [
      "Principles of Management",
      "Introduction to Marketing",
      "Business Communication",
      "Accounting Fundamentals",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "AA in Organizational Management",
    level: "Associate's",
    area: "business",
    description:
      "Build the fundamentals of organizational management and develop competencies for team leadership roles.",
    focusAreas: ["Team Leadership", "Org Behavior"],
    href: "/online-degrees/associate/organizational-management",
    credits: 60,
    duration: "As few as 18 months",
    format: "100% Online · 5-week courses",
    careerPaths: [
      { title: "Office Manager", salaryRange: "$40K–$58K" },
      { title: "Team Lead", salaryRange: "$42K–$60K" },
      { title: "Operations Coordinator", salaryRange: "$38K–$55K" },
    ],
    sampleCourses: [
      "Organizational Behavior",
      "Team Dynamics & Leadership",
      "Business Ethics",
      "Professional Communication",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Business Administration",
    level: "Bachelor's",
    area: "business",
    description:
      "Prepare for a variety of careers with core business fundamentals — finance, operations, strategy, and problem-solving skills.",
    focusAreas: ["Finance", "Strategy", "Problem-Solving"],
    href: "/online-degrees/bachelors/business-administration",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Business Analyst", salaryRange: "$60K–$90K" },
      { title: "Operations Manager", salaryRange: "$65K–$95K" },
      { title: "Financial Analyst", salaryRange: "$58K–$85K" },
      { title: "Management Consultant", salaryRange: "$70K–$110K" },
    ],
    sampleCourses: [
      "Strategic Management",
      "Managerial Finance",
      "Operations & Supply Chain",
      "Business Law",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Business Leadership",
    level: "Bachelor's",
    area: "business",
    description:
      "Develop your gift for guiding others and inspire teams to excel through evidence-based leadership practices.",
    focusAreas: ["Leadership", "Change Management"],
    href: "/online-degrees/bachelors/business-leadership",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "General Manager", salaryRange: "$62K–$95K" },
      { title: "Program Director", salaryRange: "$65K–$100K" },
      { title: "Training Manager", salaryRange: "$58K–$88K" },
    ],
    sampleCourses: [
      "Leadership Theory & Practice",
      "Change Management",
      "Organizational Communication",
      "Conflict Resolution",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Business Economics",
    level: "Bachelor's",
    area: "business",
    description:
      "Build skills in data analytics, applied economics, and business strategy for in-demand analytical roles.",
    focusAreas: ["Economics", "Data Analytics", "Strategy"],
    href: "/online-degrees/bachelors/business-economics",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Economist", salaryRange: "$65K–$105K" },
      { title: "Market Research Analyst", salaryRange: "$55K–$80K" },
      { title: "Data Analyst", salaryRange: "$58K–$85K" },
    ],
    sampleCourses: [
      "Microeconomics",
      "Macroeconomics",
      "Econometrics",
      "Business Statistics",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Human Resources Management",
    level: "Bachelor's",
    area: "business",
    description:
      "Learn talent acquisition, employee relations, compensation strategy, and organizational development.",
    focusAreas: ["Talent Management", "Employee Relations", "Compensation"],
    href: "/online-degrees/bachelors/human-resources-management",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "HR Generalist", salaryRange: "$52K–$75K" },
      { title: "Recruiter", salaryRange: "$48K–$72K" },
      { title: "Compensation Analyst", salaryRange: "$55K–$80K" },
      { title: "HR Manager", salaryRange: "$70K–$105K" },
    ],
    sampleCourses: [
      "Talent Acquisition & Retention",
      "Compensation & Benefits",
      "Employment Law",
      "Organizational Development",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Marketing",
    level: "Bachelor's",
    area: "business",
    description:
      "Master digital marketing, consumer behavior, brand strategy, and market research to drive business growth.",
    focusAreas: ["Digital Marketing", "Brand Strategy", "Research"],
    href: "/online-degrees/bachelors/marketing",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Marketing Manager", salaryRange: "$60K–$95K" },
      { title: "Digital Marketing Specialist", salaryRange: "$50K–$75K" },
      { title: "Brand Strategist", salaryRange: "$55K–$85K" },
      { title: "Market Research Analyst", salaryRange: "$52K–$78K" },
    ],
    sampleCourses: [
      "Digital Marketing Strategy",
      "Consumer Behavior",
      "Marketing Analytics",
      "Brand Management",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Project Management",
    level: "Bachelor's",
    area: "business",
    description:
      "Develop the planning, budgeting, and leadership skills needed to deliver complex projects on time and on scope.",
    focusAreas: ["Planning", "Budgeting", "Risk Management"],
    href: "/online-degrees/bachelors/project-management",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Project Manager", salaryRange: "$65K–$100K" },
      { title: "Program Coordinator", salaryRange: "$50K–$72K" },
      { title: "Scrum Master", salaryRange: "$75K–$115K" },
    ],
    sampleCourses: [
      "Project Planning & Scheduling",
      "Risk & Quality Management",
      "Agile Project Management",
      "Budgeting & Cost Control",
    ],
    accreditations: ["WSCUC Accredited"],
    certPrep: "Aligned with PMI CAPM/PMP frameworks",
  },
  {
    name: "BA in Entrepreneurship",
    level: "Bachelor's",
    area: "business",
    description:
      "Turn ideas into ventures with training in business planning, innovation, financing, and growth strategy.",
    focusAreas: ["Innovation", "Business Planning", "Financing"],
    href: "/online-degrees/bachelors/entrepreneurship",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Entrepreneur / Founder", salaryRange: "Varies" },
      { title: "Business Development Manager", salaryRange: "$60K–$95K" },
      { title: "Innovation Consultant", salaryRange: "$65K–$100K" },
    ],
    sampleCourses: [
      "New Venture Creation",
      "Business Plan Development",
      "Entrepreneurial Finance",
      "Innovation & Design Thinking",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "Master of Business Administration",
    level: "Master's",
    area: "business",
    description:
      "Advance your career with graduate-level coursework in organizational leadership, data-driven decision-making, and strategy.",
    focusAreas: ["Strategy", "Analytics", "Leadership"],
    href: "/online-degrees/masters/mba",
    credits: 36,
    duration: "As few as 15 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Senior Manager", salaryRange: "$85K–$130K" },
      { title: "Director of Operations", salaryRange: "$90K–$140K" },
      { title: "Management Consultant", salaryRange: "$95K–$150K" },
      { title: "Chief Operating Officer", salaryRange: "$120K–$200K+" },
    ],
    sampleCourses: [
      "Strategic Leadership",
      "Managerial Economics",
      "Data-Driven Decision Making",
      "Global Business Strategy",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MA in Organizational Management",
    level: "Master's",
    area: "business",
    description:
      "Deepen your management expertise with advanced study in organizational theory, strategic leadership, and change management.",
    focusAreas: ["Org Theory", "Strategic Leadership"],
    href: "/online-degrees/masters/organizational-management",
    credits: 36,
    duration: "As few as 15 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Director of Operations", salaryRange: "$80K–$120K" },
      { title: "Organizational Development Consultant", salaryRange: "$75K–$110K" },
      { title: "VP of Administration", salaryRange: "$95K–$145K" },
    ],
    sampleCourses: [
      "Advanced Organizational Theory",
      "Strategic Change Management",
      "Leadership in Complex Organizations",
      "Research Methods",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MBA in Healthcare Management",
    level: "Master's",
    area: "business",
    description:
      "Combine business acumen with healthcare industry knowledge to lead in hospitals, clinics, and health systems.",
    focusAreas: ["Healthcare Operations", "Business Strategy"],
    href: "/online-degrees/masters/mba-healthcare-management",
    credits: 48,
    duration: "As few as 20 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Healthcare Administrator", salaryRange: "$85K–$130K" },
      { title: "Hospital Operations Director", salaryRange: "$95K–$150K" },
      { title: "Health Systems Manager", salaryRange: "$80K–$120K" },
    ],
    sampleCourses: [
      "Healthcare Economics",
      "Health Systems Management",
      "Healthcare Law & Ethics",
      "Strategic Planning in Healthcare",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "PhD in Organizational Leadership",
    level: "Doctoral",
    area: "business",
    description:
      "Achieve the pinnacle of education and expertise with a doctoral degree focused on organizational transformation and research.",
    focusAreas: ["Research", "Organizational Change"],
    href: "/online-degrees/doctoral/organizational-leadership",
    credits: 60,
    duration: "As few as 3 years",
    format: "100% Online · 8-week courses",
    careerPaths: [
      { title: "University Professor", salaryRange: "$75K–$120K" },
      { title: "Chief Executive Officer", salaryRange: "$130K–$250K+" },
      { title: "Senior Research Consultant", salaryRange: "$90K–$140K" },
    ],
    sampleCourses: [
      "Doctoral Research Methods",
      "Organizational Transformation",
      "Advanced Leadership Theory",
      "Dissertation Seminar",
    ],
    accreditations: ["WSCUC Accredited"],
  },

  // ── Accounting & Finance ──────────────────────────────────────────
  {
    name: "BA in Accounting",
    level: "Bachelor's",
    area: "accounting-finance",
    description:
      "Explore relevant, rigorous, and real-world accounting curriculum covering auditing, taxation, and financial reporting.",
    focusAreas: ["Auditing", "Taxation", "Financial Reporting"],
    href: "/online-degrees/bachelors/accounting",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Accountant", salaryRange: "$52K–$78K" },
      { title: "Auditor", salaryRange: "$55K–$82K" },
      { title: "Tax Specialist", salaryRange: "$50K–$75K" },
      { title: "Financial Controller", salaryRange: "$72K–$110K" },
    ],
    sampleCourses: [
      "Intermediate Accounting",
      "Auditing Principles",
      "Federal Taxation",
      "Cost Accounting",
    ],
    accreditations: ["WSCUC Accredited"],
    certPrep: "Coursework supports CPA exam preparation",
  },
  {
    name: "BA in Finance",
    level: "Bachelor's",
    area: "accounting-finance",
    description:
      "Invest in your career with courses in markets, investments, risk management, and micro and macroeconomics.",
    focusAreas: ["Investments", "Risk Management", "Economics"],
    href: "/online-degrees/bachelors/finance",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Financial Analyst", salaryRange: "$58K–$88K" },
      { title: "Investment Analyst", salaryRange: "$62K–$95K" },
      { title: "Risk Manager", salaryRange: "$65K–$100K" },
    ],
    sampleCourses: [
      "Corporate Finance",
      "Investment Analysis",
      "Financial Markets",
      "Risk Management",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Financial Planning",
    level: "Bachelor's",
    area: "accounting-finance",
    description:
      "Prepare for a career as a financial planner with coursework in retirement planning, taxation, estate planning, and investment management.",
    focusAreas: ["Retirement Planning", "Taxation", "Investment"],
    href: "/online-degrees/bachelors/financial-planning",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Financial Planner", salaryRange: "$58K–$95K" },
      { title: "Wealth Advisor", salaryRange: "$62K–$110K" },
      { title: "Retirement Specialist", salaryRange: "$55K–$82K" },
    ],
    sampleCourses: [
      "Retirement Planning",
      "Estate Planning",
      "Investment Management",
      "Tax Planning Strategies",
    ],
    accreditations: ["WSCUC Accredited"],
    certPrep: "CFP Board-registered program",
  },
  {
    name: "MS in Accounting",
    level: "Master's",
    area: "accounting-finance",
    description:
      "Advance your accounting expertise with graduate-level study in forensic accounting, auditing standards, and regulatory compliance.",
    focusAreas: ["Forensic Accounting", "Compliance", "Auditing"],
    href: "/online-degrees/masters/accounting",
    credits: 30,
    duration: "As few as 12 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Senior Auditor", salaryRange: "$70K–$100K" },
      { title: "Forensic Accountant", salaryRange: "$72K–$105K" },
      { title: "Compliance Officer", salaryRange: "$68K–$98K" },
      { title: "CFO", salaryRange: "$110K–$180K+" },
    ],
    sampleCourses: [
      "Forensic Accounting",
      "Advanced Auditing",
      "Regulatory Compliance",
      "Accounting Information Systems",
    ],
    accreditations: ["WSCUC Accredited"],
    certPrep: "Meets CPA exam credit-hour requirements in many states",
  },

  // ── Criminal Justice ──────────────────────────────────────────────
  {
    name: "AA in Criminal Justice",
    level: "Associate's",
    area: "criminal-justice",
    description:
      "Get a strong foundation in the criminal justice system including policing, courts, corrections, and juvenile justice.",
    focusAreas: ["Policing", "Courts", "Corrections"],
    href: "/online-degrees/associate/criminal-justice",
    credits: 60,
    duration: "As few as 18 months",
    format: "100% Online · 5-week courses",
    careerPaths: [
      { title: "Correctional Officer", salaryRange: "$38K–$55K" },
      { title: "Security Specialist", salaryRange: "$35K–$50K" },
      { title: "Court Clerk", salaryRange: "$36K–$48K" },
    ],
    sampleCourses: [
      "Introduction to Criminal Justice",
      "Policing in America",
      "Juvenile Justice",
      "Criminal Law",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Criminal Justice",
    level: "Bachelor's",
    area: "criminal-justice",
    description:
      "Develop skills in law enforcement, corrections, and homeland security while studying the justice system.",
    focusAreas: ["Law Enforcement", "Corrections", "Homeland Security"],
    href: "/online-degrees/bachelors/criminal-justice",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Police Officer", salaryRange: "$48K–$72K" },
      { title: "Probation Officer", salaryRange: "$45K–$65K" },
      { title: "Criminal Investigator", salaryRange: "$55K–$85K" },
      { title: "FBI/DEA Agent", salaryRange: "$62K–$100K" },
    ],
    sampleCourses: [
      "Criminological Theory",
      "Criminal Investigation",
      "Ethics in Criminal Justice",
      "Victimology",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Homeland Security",
    level: "Bachelor's",
    area: "criminal-justice",
    description:
      "Study emergency management, intelligence analysis, and national security policy in an increasingly connected world.",
    focusAreas: ["Emergency Management", "Intelligence", "Security Policy"],
    href: "/online-degrees/bachelors/homeland-security",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Emergency Management Director", salaryRange: "$60K–$90K" },
      { title: "Intelligence Analyst", salaryRange: "$58K–$88K" },
      { title: "Security Consultant", salaryRange: "$62K–$95K" },
    ],
    sampleCourses: [
      "Homeland Security Policy",
      "Emergency Preparedness",
      "Intelligence Analysis",
      "Critical Infrastructure Protection",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Cybercrime & Security",
    level: "Bachelor's",
    area: "criminal-justice",
    description:
      "Explore digital forensics, cybersecurity law, and threat analysis at the intersection of technology and justice.",
    focusAreas: ["Digital Forensics", "Cybersecurity Law", "Threat Analysis"],
    href: "/online-degrees/bachelors/cybercrime-security",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Cybercrime Analyst", salaryRange: "$58K–$88K" },
      { title: "Digital Forensics Examiner", salaryRange: "$62K–$95K" },
      { title: "Information Security Analyst", salaryRange: "$70K–$110K" },
    ],
    sampleCourses: [
      "Digital Forensics",
      "Cybersecurity Law",
      "Network Threat Analysis",
      "Cybercrime Investigation",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MS in Criminal Justice",
    level: "Master's",
    area: "criminal-justice",
    description:
      "Advance your expertise in criminology, policy analysis, and justice system leadership at the graduate level.",
    focusAreas: ["Criminology", "Policy", "Leadership"],
    href: "/online-degrees/masters/criminal-justice",
    credits: 36,
    duration: "As few as 15 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Criminal Justice Director", salaryRange: "$72K–$110K" },
      { title: "Policy Analyst", salaryRange: "$65K–$95K" },
      { title: "Chief of Police", salaryRange: "$85K–$135K" },
    ],
    sampleCourses: [
      "Advanced Criminology",
      "Criminal Justice Policy",
      "Research Methods",
      "Justice Administration",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MA in Legal Studies",
    level: "Master's",
    area: "criminal-justice",
    description:
      "Build advanced knowledge of the legal system, regulatory frameworks, and compliance for non-attorney professionals.",
    focusAreas: ["Legal Research", "Regulatory Compliance", "Advocacy"],
    href: "/online-degrees/masters/legal-studies",
    credits: 36,
    duration: "As few as 15 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Compliance Manager", salaryRange: "$68K–$100K" },
      { title: "Legal Analyst", salaryRange: "$58K–$85K" },
      { title: "Regulatory Affairs Specialist", salaryRange: "$65K–$95K" },
    ],
    sampleCourses: [
      "Legal Research & Writing",
      "Regulatory Frameworks",
      "Constitutional Law",
      "Alternative Dispute Resolution",
    ],
    accreditations: ["WSCUC Accredited"],
  },

  // ── Education ─────────────────────────────────────────────────────
  {
    name: "AA in Early Childhood Education",
    level: "Associate's",
    area: "education",
    description:
      "Prepare to work in childcare as you learn the foundations of childhood development and classroom strategies.",
    focusAreas: ["Child Development", "Classroom Strategies"],
    href: "/online-degrees/associate/early-childhood-education",
    credits: 60,
    duration: "As few as 18 months",
    format: "100% Online · 5-week courses",
    careerPaths: [
      { title: "Childcare Worker", salaryRange: "$28K–$38K" },
      { title: "Teacher Assistant", salaryRange: "$28K–$36K" },
      { title: "Preschool Teacher", salaryRange: "$30K–$42K" },
    ],
    sampleCourses: [
      "Child Development Foundations",
      "Early Childhood Curriculum",
      "Classroom Management",
      "Creative Arts for Young Learners",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Education Studies",
    level: "Bachelor's",
    area: "education",
    description:
      "Amplify your impact in education with training in instructional methods, curriculum design, and learning theory.",
    focusAreas: ["Instructional Methods", "Curriculum Design"],
    href: "/online-degrees/bachelors/education-studies",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Instructional Coordinator", salaryRange: "$50K–$72K" },
      { title: "Corporate Trainer", salaryRange: "$52K–$75K" },
      { title: "Education Program Manager", salaryRange: "$48K–$68K" },
    ],
    sampleCourses: [
      "Foundations of Education",
      "Instructional Strategies",
      "Curriculum Development",
      "Educational Psychology",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Elementary Education",
    level: "Bachelor's",
    area: "education",
    description:
      "Prepare for teacher licensure with hands-on training in classroom management, assessment, and K–6 instructional strategies.",
    focusAreas: ["K–6 Instruction", "Classroom Management", "Assessment"],
    href: "/online-degrees/bachelors/elementary-education",
    credits: 120,
    duration: "As few as 3.5 years",
    format: "100% Online · Includes student teaching",
    careerPaths: [
      { title: "Elementary School Teacher", salaryRange: "$42K–$65K" },
      { title: "Curriculum Specialist", salaryRange: "$50K–$72K" },
      { title: "Reading Specialist", salaryRange: "$48K–$68K" },
    ],
    sampleCourses: [
      "Literacy Instruction K–6",
      "Mathematics Methods",
      "Science & Social Studies Methods",
      "Student Teaching Practicum",
    ],
    accreditations: ["WSCUC Accredited"],
    certPrep: "Leads to teacher licensure (state requirements vary)",
  },
  {
    name: "BA in Special Education",
    level: "Bachelor's",
    area: "education",
    description:
      "Learn to support learners with diverse needs through specialized instruction, IEP development, and inclusive classroom design.",
    focusAreas: ["IEP Development", "Inclusive Design", "Adaptive Teaching"],
    href: "/online-degrees/bachelors/special-education",
    credits: 120,
    duration: "As few as 3.5 years",
    format: "100% Online · Includes student teaching",
    careerPaths: [
      { title: "Special Education Teacher", salaryRange: "$45K–$68K" },
      { title: "Behavior Specialist", salaryRange: "$42K–$60K" },
      { title: "IEP Coordinator", salaryRange: "$48K–$65K" },
    ],
    sampleCourses: [
      "Foundations of Special Education",
      "IEP Development & Management",
      "Inclusive Classroom Strategies",
      "Assessment for Diverse Learners",
    ],
    accreditations: ["WSCUC Accredited"],
    certPrep: "Leads to special education licensure (state requirements vary)",
  },
  {
    name: "MA in Education",
    level: "Master's",
    area: "education",
    description:
      "Deepen your expertise in educational leadership, assessment, and evidence-based teaching practice.",
    focusAreas: ["Ed Leadership", "Assessment", "Teaching Practice"],
    href: "/online-degrees/masters/education",
    credits: 30,
    duration: "As few as 12 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Lead Teacher", salaryRange: "$55K–$78K" },
      { title: "Academic Coach", salaryRange: "$52K–$72K" },
      { title: "Curriculum Director", salaryRange: "$65K–$95K" },
    ],
    sampleCourses: [
      "Advanced Pedagogy",
      "Educational Assessment",
      "Action Research in Education",
      "Technology-Enhanced Learning",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MA in Curriculum & Instruction",
    level: "Master's",
    area: "education",
    description:
      "Design and evaluate curricula that improve student outcomes using current research and instructional technology.",
    focusAreas: ["Curriculum Design", "Instructional Tech", "Research"],
    href: "/online-degrees/masters/curriculum-instruction",
    credits: 30,
    duration: "As few as 12 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Curriculum Designer", salaryRange: "$55K–$80K" },
      { title: "Instructional Technologist", salaryRange: "$58K–$85K" },
      { title: "Director of Curriculum", salaryRange: "$70K–$100K" },
    ],
    sampleCourses: [
      "Curriculum Theory & Design",
      "Instructional Technology Integration",
      "Assessment & Evaluation",
      "Educational Research Methods",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MA in Educational Leadership",
    level: "Master's",
    area: "education",
    description:
      "Prepare for school administration and district leadership roles with training in policy, governance, and organizational change.",
    focusAreas: ["School Admin", "Policy", "Governance"],
    href: "/online-degrees/masters/educational-leadership",
    credits: 30,
    duration: "As few as 12 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "School Principal", salaryRange: "$75K–$115K" },
      { title: "District Administrator", salaryRange: "$80K–$120K" },
      { title: "Dean of Students", salaryRange: "$65K–$95K" },
    ],
    sampleCourses: [
      "School Law & Governance",
      "Instructional Leadership",
      "School Finance & Budgeting",
      "Community & Stakeholder Engagement",
    ],
    accreditations: ["WSCUC Accredited"],
    certPrep: "Aligned with principal/administrator licensure requirements",
  },

  // ── Health Care ───────────────────────────────────────────────────
  {
    name: "AA in Health Sciences",
    level: "Associate's",
    area: "health-care",
    description:
      "Build a foundation in health science principles including anatomy, medical terminology, and patient care basics.",
    focusAreas: ["Anatomy", "Medical Terminology", "Patient Care"],
    href: "/online-degrees/associate/health-sciences",
    credits: 60,
    duration: "As few as 18 months",
    format: "100% Online · 5-week courses",
    careerPaths: [
      { title: "Medical Assistant", salaryRange: "$32K–$42K" },
      { title: "Health Information Technician", salaryRange: "$35K–$48K" },
      { title: "Patient Care Coordinator", salaryRange: "$34K–$45K" },
    ],
    sampleCourses: [
      "Anatomy & Physiology",
      "Medical Terminology",
      "Introduction to Health Sciences",
      "Patient Care Fundamentals",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Health Care Administration",
    level: "Bachelor's",
    area: "health-care",
    description:
      "Prepare for leadership roles in health care organizations covering administration, policy, and patient services.",
    focusAreas: ["Administration", "Health Policy", "Patient Services"],
    href: "/online-degrees/bachelors/health-care-administration",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Healthcare Administrator", salaryRange: "$55K–$82K" },
      { title: "Medical Office Manager", salaryRange: "$48K–$68K" },
      { title: "Health Services Manager", salaryRange: "$62K–$95K" },
    ],
    sampleCourses: [
      "Healthcare Administration",
      "Health Policy & Law",
      "Healthcare Quality Management",
      "Health Economics",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BS in Health Information Management",
    level: "Bachelor's",
    area: "health-care",
    description:
      "Learn to manage health data systems, ensure regulatory compliance, and improve health information workflows. CAHIIM-accredited.",
    focusAreas: ["Health Data", "Compliance", "Informatics"],
    href: "/online-degrees/bachelors/health-information-management",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Health Information Manager", salaryRange: "$55K–$80K" },
      { title: "Clinical Data Analyst", salaryRange: "$52K–$75K" },
      { title: "Health IT Project Manager", salaryRange: "$65K–$95K" },
    ],
    sampleCourses: [
      "Health Information Systems",
      "Medical Coding & Classification",
      "Healthcare Data Analytics",
      "HIPAA & Regulatory Compliance",
    ],
    accreditations: ["WSCUC Accredited", "CAHIIM Accredited"],
    certPrep: "Prepares for RHIA certification exam",
  },
  {
    name: "BS in Nursing (RN-to-BSN)",
    level: "Bachelor's",
    area: "health-care",
    description:
      "Advance your nursing career with a CCNE-accredited BSN designed for working registered nurses.",
    focusAreas: ["Nursing Leadership", "Evidence-Based Practice"],
    href: "/online-degrees/bachelors/nursing-rn-bsn",
    credits: 120,
    duration: "As few as 12 months",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Registered Nurse (BSN)", salaryRange: "$65K–$90K" },
      { title: "Nurse Manager", salaryRange: "$78K–$110K" },
      { title: "Public Health Nurse", salaryRange: "$60K–$82K" },
    ],
    sampleCourses: [
      "Evidence-Based Nursing Practice",
      "Nursing Leadership & Management",
      "Community Health Nursing",
      "Nursing Informatics",
    ],
    accreditations: ["WSCUC Accredited", "CCNE Accredited"],
  },
  {
    name: "Master of Public Health",
    level: "Master's",
    area: "health-care",
    description:
      "Gain advanced knowledge in epidemiology, community health, and health systems management.",
    focusAreas: ["Epidemiology", "Community Health", "Health Systems"],
    href: "/online-degrees/masters/public-health",
    credits: 42,
    duration: "As few as 18 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Epidemiologist", salaryRange: "$60K–$95K" },
      { title: "Public Health Director", salaryRange: "$72K–$110K" },
      { title: "Health Program Manager", salaryRange: "$65K–$92K" },
    ],
    sampleCourses: [
      "Epidemiology",
      "Biostatistics",
      "Health Policy & Management",
      "Environmental Health",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MS in Health Administration",
    level: "Master's",
    area: "health-care",
    description:
      "Prepare for executive-level health care leadership with training in operations, finance, and strategic planning.",
    focusAreas: ["Healthcare Operations", "Finance", "Strategic Planning"],
    href: "/online-degrees/masters/health-administration",
    credits: 36,
    duration: "As few as 15 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Hospital Administrator", salaryRange: "$85K–$130K" },
      { title: "VP of Health Services", salaryRange: "$100K–$160K" },
      { title: "Healthcare COO", salaryRange: "$110K–$175K" },
    ],
    sampleCourses: [
      "Healthcare Financial Management",
      "Strategic Planning in Healthcare",
      "Healthcare Operations Management",
      "Health Law & Compliance",
    ],
    accreditations: ["WSCUC Accredited"],
  },

  // ── Information Technology ────────────────────────────────────────
  {
    name: "BA in Business Information Systems",
    level: "Bachelor's",
    area: "information-technology",
    description:
      "Build skills at the intersection of business and modern technology platforms including systems analysis and data management.",
    focusAreas: ["Systems Analysis", "Data Management"],
    href: "/online-degrees/bachelors/business-information-systems",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Business Systems Analyst", salaryRange: "$60K–$90K" },
      { title: "IT Project Manager", salaryRange: "$68K–$100K" },
      { title: "Database Administrator", salaryRange: "$62K–$92K" },
    ],
    sampleCourses: [
      "Systems Analysis & Design",
      "Database Management",
      "Business Process Modeling",
      "Enterprise Architecture",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BS in Information Technology",
    level: "Bachelor's",
    area: "information-technology",
    description:
      "Learn the fundamentals of modern tech — networking, cybersecurity, and systems development.",
    focusAreas: ["Networking", "Cybersecurity", "Development"],
    href: "/online-degrees/bachelors/information-technology",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "IT Specialist", salaryRange: "$55K–$80K" },
      { title: "Network Administrator", salaryRange: "$58K–$85K" },
      { title: "Systems Administrator", salaryRange: "$62K–$92K" },
      { title: "IT Manager", salaryRange: "$75K–$115K" },
    ],
    sampleCourses: [
      "Networking Fundamentals",
      "Cybersecurity Principles",
      "Systems Development",
      "Cloud Computing",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BS in Cybersecurity",
    level: "Bachelor's",
    area: "information-technology",
    description:
      "Protect organizations from digital threats with training in network security, ethical hacking, and incident response.",
    focusAreas: ["Network Security", "Ethical Hacking", "Incident Response"],
    href: "/online-degrees/bachelors/cybersecurity",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Cybersecurity Analyst", salaryRange: "$72K–$110K" },
      { title: "Penetration Tester", salaryRange: "$78K–$120K" },
      { title: "Security Engineer", salaryRange: "$85K–$130K" },
    ],
    sampleCourses: [
      "Ethical Hacking",
      "Network Defense",
      "Incident Response & Forensics",
      "Security Architecture",
    ],
    accreditations: ["WSCUC Accredited"],
    certPrep: "Aligned with CompTIA Security+ and CISSP frameworks",
  },
  {
    name: "BS in Data Management & Analytics",
    level: "Bachelor's",
    area: "information-technology",
    description:
      "Turn raw data into business insights with training in SQL, data visualization, statistical analysis, and database administration.",
    focusAreas: ["SQL", "Data Visualization", "Statistical Analysis"],
    href: "/online-degrees/bachelors/data-management-analytics",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Data Analyst", salaryRange: "$58K–$85K" },
      { title: "Business Intelligence Analyst", salaryRange: "$65K–$98K" },
      { title: "Database Manager", salaryRange: "$70K–$105K" },
    ],
    sampleCourses: [
      "SQL & Database Design",
      "Data Visualization",
      "Statistical Analysis",
      "Big Data Fundamentals",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MS in Information Systems Management",
    level: "Master's",
    area: "information-technology",
    description:
      "Lead technology strategy with graduate-level training in information architecture and enterprise systems.",
    focusAreas: ["Enterprise Systems", "IT Strategy"],
    href: "/online-degrees/masters/information-systems",
    credits: 36,
    duration: "As few as 15 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "IT Director", salaryRange: "$95K–$145K" },
      { title: "CTO / CIO", salaryRange: "$120K–$200K+" },
      { title: "Enterprise Architect", salaryRange: "$100K–$155K" },
    ],
    sampleCourses: [
      "IT Governance & Strategy",
      "Enterprise Architecture",
      "Advanced Project Management",
      "Cybersecurity Management",
    ],
    accreditations: ["WSCUC Accredited"],
  },

  // ── Liberal Arts ──────────────────────────────────────────────────
  {
    name: "AA in General Studies",
    level: "Associate's",
    area: "liberal-arts",
    description:
      "Explore a broad curriculum in communication, critical thinking, and the humanities as a foundation for a bachelor's degree.",
    focusAreas: ["Communication", "Critical Thinking", "Humanities"],
    href: "/online-degrees/associate/general-studies",
    credits: 60,
    duration: "As few as 18 months",
    format: "100% Online · 5-week courses",
    careerPaths: [
      { title: "Administrative Coordinator", salaryRange: "$35K–$48K" },
      { title: "Community Outreach Worker", salaryRange: "$32K–$45K" },
      { title: "Customer Relations Specialist", salaryRange: "$34K–$48K" },
    ],
    sampleCourses: [
      "English Composition",
      "Critical Thinking",
      "Introduction to Humanities",
      "Interpersonal Communication",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "AA in Military Studies",
    level: "Associate's",
    area: "liberal-arts",
    description:
      "Explore global security challenges, military affairs, and leadership principles for service members and veterans.",
    focusAreas: ["Military Affairs", "Global Security", "Leadership"],
    href: "/online-degrees/associate/military-studies",
    credits: 60,
    duration: "As few as 18 months",
    format: "100% Online · 5-week courses",
    careerPaths: [
      { title: "Military Intelligence Analyst", salaryRange: "$45K–$68K" },
      { title: "Defense Contractor", salaryRange: "$50K–$75K" },
      { title: "Veterans Services Coordinator", salaryRange: "$38K–$55K" },
    ],
    sampleCourses: [
      "Military History",
      "Global Security Studies",
      "Leadership in Military Context",
      "Geopolitical Analysis",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Liberal Arts",
    level: "Bachelor's",
    area: "liberal-arts",
    description:
      "Challenge the status quo and expand your thinking across humanities, social sciences, and communication.",
    focusAreas: ["Humanities", "Social Sciences", "Communication"],
    href: "/online-degrees/bachelors/liberal-arts",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Communications Specialist", salaryRange: "$45K–$68K" },
      { title: "Content Writer", salaryRange: "$42K–$65K" },
      { title: "Nonprofit Program Manager", salaryRange: "$48K–$72K" },
    ],
    sampleCourses: [
      "Philosophy & Ethics",
      "World Literature",
      "Art History",
      "Advanced Composition",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in English",
    level: "Bachelor's",
    area: "liberal-arts",
    description:
      "Develop advanced writing, analysis, and communication skills through the study of literature, rhetoric, and language.",
    focusAreas: ["Writing", "Literature", "Rhetoric"],
    href: "/online-degrees/bachelors/english",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Technical Writer", salaryRange: "$55K–$82K" },
      { title: "Editor", salaryRange: "$48K–$72K" },
      { title: "Content Strategist", salaryRange: "$52K–$78K" },
    ],
    sampleCourses: [
      "American Literature",
      "Rhetorical Analysis",
      "Creative Writing",
      "Advanced Grammar & Editing",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Communication Studies",
    level: "Bachelor's",
    area: "liberal-arts",
    description:
      "Study interpersonal, organizational, and mass communication to build skills for media, PR, and corporate settings.",
    focusAreas: ["Media", "Public Relations", "Org Communication"],
    href: "/online-degrees/bachelors/communication-studies",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Public Relations Specialist", salaryRange: "$48K–$72K" },
      { title: "Media Coordinator", salaryRange: "$42K–$62K" },
      { title: "Corporate Communications Manager", salaryRange: "$62K–$92K" },
    ],
    sampleCourses: [
      "Mass Communication",
      "Public Relations Strategy",
      "Organizational Communication",
      "Media & Society",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Political Science",
    level: "Bachelor's",
    area: "liberal-arts",
    description:
      "Analyze political systems, public policy, and governance to prepare for careers in government, law, or advocacy.",
    focusAreas: ["Public Policy", "Governance", "Political Theory"],
    href: "/online-degrees/bachelors/political-science",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Policy Analyst", salaryRange: "$52K–$78K" },
      { title: "Government Affairs Specialist", salaryRange: "$55K–$82K" },
      { title: "Campaign Manager", salaryRange: "$48K–$75K" },
    ],
    sampleCourses: [
      "American Government",
      "Comparative Politics",
      "Public Policy Analysis",
      "International Relations",
    ],
    accreditations: ["WSCUC Accredited"],
  },

  // ── Social & Behavioral Science ───────────────────────────────────
  {
    name: "BA in Applied Behavioral Science",
    level: "Bachelor's",
    area: "social-behavioral",
    description:
      "Use your knowledge of human behavior to solve problems facing organizations and communities.",
    focusAreas: ["Behavioral Analysis", "Org Psychology"],
    href: "/online-degrees/bachelors/applied-behavioral-science",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Behavioral Health Technician", salaryRange: "$35K–$48K" },
      { title: "Case Manager", salaryRange: "$38K–$52K" },
      { title: "Community Program Coordinator", salaryRange: "$40K–$58K" },
    ],
    sampleCourses: [
      "Applied Behavior Analysis",
      "Social Psychology",
      "Research Methods in Behavioral Science",
      "Community Intervention Strategies",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Psychology",
    level: "Bachelor's",
    area: "social-behavioral",
    description:
      "Study the science of mind and behavior with coursework in research methods, cognition, and developmental psychology.",
    focusAreas: ["Research Methods", "Cognition", "Development"],
    href: "/online-degrees/bachelors/psychology",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Mental Health Technician", salaryRange: "$32K–$45K" },
      { title: "Research Assistant", salaryRange: "$35K–$48K" },
      { title: "Human Services Worker", salaryRange: "$34K–$48K" },
      { title: "Behavioral Health Manager", salaryRange: "$50K–$72K" },
    ],
    sampleCourses: [
      "Abnormal Psychology",
      "Cognitive Psychology",
      "Developmental Psychology",
      "Research Methods & Statistics",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Sociology",
    level: "Bachelor's",
    area: "social-behavioral",
    description:
      "Examine social structures, inequality, and group dynamics to understand and address societal challenges.",
    focusAreas: ["Social Structures", "Inequality", "Group Dynamics"],
    href: "/online-degrees/bachelors/sociology",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Social Worker (entry-level)", salaryRange: "$38K–$52K" },
      { title: "Community Organizer", salaryRange: "$36K–$50K" },
      { title: "Policy Research Analyst", salaryRange: "$45K–$65K" },
    ],
    sampleCourses: [
      "Introduction to Sociology",
      "Social Inequality",
      "Race & Ethnicity",
      "Sociological Research Methods",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "BA in Social Science",
    level: "Bachelor's",
    area: "social-behavioral",
    description:
      "Take an interdisciplinary approach to understanding human society through psychology, sociology, and political science.",
    focusAreas: ["Interdisciplinary", "Society", "Behavior"],
    href: "/online-degrees/bachelors/social-science",
    credits: 120,
    duration: "As few as 3 years",
    format: "100% Online · 5- or 6-week courses",
    careerPaths: [
      { title: "Social Services Coordinator", salaryRange: "$38K–$55K" },
      { title: "Program Analyst", salaryRange: "$42K–$62K" },
      { title: "Community Health Worker", salaryRange: "$35K–$50K" },
    ],
    sampleCourses: [
      "Social Science Research Methods",
      "Cultural Anthropology",
      "Introduction to Political Science",
      "Social Problems & Solutions",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MA in Psychology",
    level: "Master's",
    area: "social-behavioral",
    description:
      "Deepen your understanding of psychological theory and applied research at the graduate level.",
    focusAreas: ["Applied Research", "Theory", "Clinical Practice"],
    href: "/online-degrees/masters/psychology",
    credits: 36,
    duration: "As few as 15 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Clinical Case Manager", salaryRange: "$48K–$68K" },
      { title: "Behavioral Health Counselor", salaryRange: "$52K–$75K" },
      { title: "Research Coordinator", salaryRange: "$50K–$72K" },
    ],
    sampleCourses: [
      "Advanced Psychological Theory",
      "Applied Research Design",
      "Clinical Assessment",
      "Psychopharmacology",
    ],
    accreditations: ["WSCUC Accredited"],
  },
  {
    name: "MS in Applied Behavioral Analysis",
    level: "Master's",
    area: "social-behavioral",
    description:
      "Train for BCBA certification eligibility with advanced study in behavior assessment, intervention design, and ethical practice.",
    focusAreas: ["BCBA Prep", "Intervention Design", "Ethics"],
    href: "/online-degrees/masters/applied-behavioral-analysis",
    credits: 42,
    duration: "As few as 18 months",
    format: "100% Online · 6-week courses",
    careerPaths: [
      { title: "Board Certified Behavior Analyst", salaryRange: "$58K–$85K" },
      { title: "ABA Therapist (Supervisor)", salaryRange: "$55K–$78K" },
      { title: "Clinical Director (ABA)", salaryRange: "$72K–$105K" },
    ],
    sampleCourses: [
      "Principles of ABA",
      "Behavior Assessment & Intervention",
      "Ethics in Behavior Analysis",
      "Supervised Fieldwork",
    ],
    accreditations: ["WSCUC Accredited", "ABAI Verified Course Sequence"],
    certPrep: "Meets BCBA certification coursework requirements",
  },
];
